### ISSUE TITLE
Race condition in BasicSecurityService?

### ISSUE THREAD

**Issue by ChrisSimmons** [jamiekurtz/WebApi2Book#2]
On pp123-124, I see that `BasicSecurityService` is registered with Ninject as a singleton, and with the justification that "`BasicSecurityService` stores no state itself."  While that may be true, I think there may be a race condition in [`SetPrincipal()`](https://github.com/jamiekurtz/WebApi2Book/blob/completed/src/WebApi2Book.Web.Api/Security/BasicSecurityService.cs#L37). Although unlikely, it's possible that multiple threads could be tripping over each other as they both work with the method-local `user` and `principal` variables.  By the time an early thread gets to lines [48](https://github.com/jamiekurtz/WebApi2Book/blob/completed/src/WebApi2Book.Web.Api/Security/BasicSecurityService.cs#L48) or [51](https://github.com/jamiekurtz/WebApi2Book/blob/completed/src/WebApi2Book.Web.Api/Security/BasicSecurityService.cs#L51), later threads could have easily redefined `principal` back on line [42](https://github.com/jamiekurtz/WebApi2Book/blob/completed/src/WebApi2Book.Web.Api/Security/BasicSecurityService.cs#L42).  Imagine thread 1 coming in as "bhogg" but ends up with principal "jdoe" since thread 2 redefined `principal` before thread 1 could set the appropriate thread and context principals.

If I'm correct, I think the fix here is to simply register `BasicSecurityService` in request scope.

**Comment by ChrisSimmons** [comment]
Nope.  This is my own misunderstanding of basic thread/method workings.  Please disregard.

**Comment by jamiekurtz** [comment]
No worries.., my apologies for the delayed response... here's what I was going to write - which you're no doubt thinking the same now, too:

I suppose there's an assumption that we have one thread per request. The only way that code would be problematic would be if a request had more than one thread - which isn't the execution model for ASP.NET, as far as I know.

There also seems to be a bit of confusion regarding local variables and thinking they are static along with the class??

Let me know if this isn't clear, or you do indeed find a problem! And again, sorry for the delay in getting back to you.

**Comment by ChrisSimmons** [comment]
Your last point was exactly my problem: operating under the mistaken assumption that the method-local variables were being shared with all threads.  Of course, I was wrong.  Even with a singleton or static classes, each thread is going to get its own "instance" of the method and its local variables on its own stack of execution.  You were exactly correct in the book that, since there's no shared state in the class, it's safe to have a singleton.

Embarrassing mistake for me there.  :)  Sorry for the bother.
